packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - argon2
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
