ALTER TYPE "BillingPlanKey" ADD VALUE IF NOT EXISTS 'FLEX';

ALTER TYPE "BillingAddonKey" ADD VALUE IF NOT EXISTS 'JOB_CREDIT_PACK_1';
ALTER TYPE "BillingAddonKey" ADD VALUE IF NOT EXISTS 'JOB_CREDIT_PACK_3';

ALTER TABLE "BillingQuotaGrant"
ADD COLUMN "consumedQuantity" INTEGER NOT NULL DEFAULT 0;
