import type { Permission, Role } from "@ai-interviewer/domain";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  admin: [
    "tenant.manage",
    "workspace.manage",
    "user.manage",
    "job.create",
    "job.read",
    "job.update",
    "candidate.create",
    "candidate.read",
    "candidate.move_stage",
    "screening.template.manage",
    "screening.run",
    "interview.template.manage",
    "interview.schedule",
    "interview.read",
    "interview.session.manage",
    "ai.task.request",
    "ai.task.read",
    "ai.report.read",
    "report.generate",
    "report.read",
    "recommendation.read",
    "ai.config.update",
    "workflow.manage",
    "integration.manage",
    "notification.send",
    "audit.read"
  ],
  recruiter: [
    "job.create",
    "job.read",
    "job.update",
    "candidate.create",
    "candidate.read",
    "candidate.move_stage",
    "screening.run",
    "interview.template.manage",
    "interview.schedule",
    "interview.read",
    "interview.session.manage",
    "ai.task.request",
    "ai.task.read",
    "ai.report.read",
    "report.generate",
    "report.read",
    "recommendation.read",
    "ai.config.update",
    "audit.read"
  ],
  hiring_manager: [
    "job.read",
    "candidate.read",
    "interview.read",
    "ai.task.read",
    "ai.report.read",
    "report.read",
    "recommendation.read"
  ],
  candidate: [],
  agency_recruiter: ["candidate.create", "candidate.read", "job.read", "ai.task.read"]
};
